export const emojis: Record<string, string> = {
  dog: "🐶",
  dogs: "🐶",
  puppy: "🐶",
  wolf: "🐺",
  wolves: "🐺",
  purple: "🟣",
  dinosaur: "🦖",
  fox: "🦊",
  mad: "🤪",
  crab: "🦀",
  vending: "🤑",
  quacking: "🦆",
  brown: "🟤",
  whale: "🐋",
};
